{
  "openapi":"3.0.2",
  "info": {
    "title":"API for contact service",
    "version":"1.0"
  },
  "servers": [
    {
      "url":"https://localhost:8000",
      "description": "adalah url server untuk seluruh service yang ada"
    }
  ],
  "paths": {
    "/api/contacts": {
      "post":{
        "description": "membuat contact baru",
        "parameters": [
          {
            "$ref": "#/components/parameters/authorization"
          }
        ],
        "requestBody":{
          "description": "request body untuk membuat contact baru",
          "required": true,
          "content": {
            "application/json":{
              "schema":{
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName":{
                    "type": "string"
                  },
                  "email":{
                    "type": "string"
                  },
                  "phone":{
                    "type": "string"
                  },
                  "address":{
                    "type": "string"
                  }
                }
              },
              "examples": {
                "james":{
                  "description": "contoh untuk james",
                  "value":{
                    "firstName": "james",
                    "lastname": "maubila",
                    "email": "james maubila",
                    "phone": "081234567899"
                  }
                },
                "putri":{
                  "description": "contoh untuk putri",
                  "value":{
                    "firstName": "putri",
                    "lastname": "rahmatia",
                    "email": "putri rahmatia",
                    "phonr": "081234567888"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "berhasil menyimpan data ke sistem",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "firstName": {
                          "type": "string"
                        },
                        "lastName": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "address": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "application/json": {
                    "status": 200,
                    "message": "berhasil menyimpan data ke sistem",
                    "data": {
                      "id": 1,
                      "firstName": "james",
                      "lastName": "maubila",
                      "email": "johndoe@example.com",
                      "address": "sikumana"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get":{
        "description": "mendapatkan contact dan melakukan pencarian",
        "parameters": [
          {
            "$ref": "#/components/parameters/authorization"
          }
        ],
        "requestBody":{
          "description": "",
          "content": {}
        },
        "responses": {
          "200":{
            "description": ""
          }
        }
      }
    },
    "/api/contact/{id}":{
      "parameters": [
        {
          "$ref": "#/components/parameters/authorization"
        },
        {
          "$ref": "#/components/parameters/getWhereId"
        }
      ],
      "put":{
        "description": "memperbaharui data contact baru",
        "requestBody":{
          "description": "request body untuk membuat contact baru",
          "required": true,
          "content": {
            "application/json":{
              "schema":{
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName":{
                    "type": "string"
                  },
                  "email":{
                    "type": "string"
                  },
                  "phone":{
                    "type": "string"
                  },
                  "address":{
                    "type": "string"
                  }
                }
              },
              "examples": {
                "james":{
                  "description": "contoh untuk james",
                  "value":{
                    "firstName": "james",
                    "lastname": "maubila",
                    "email": "james maubila",
                    "phone": "081234567899"
                  }
                },
                "putri":{
                  "description": "contoh untuk putri",
                  "value":{
                    "firstName": "putri",
                    "lastname": "rahmatia",
                    "email": "putri rahmatia",
                    "phonr": "081234567888"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "berhasil menyimpan data ke sistem",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "firstName": {
                          "type": "string"
                        },
                        "lastName": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "address": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "application/json": {
                    "status": 200,
                    "message": "berhasil menyimpan data ke sistem",
                    "data": {
                      "id": 1,
                      "firstName": "james",
                      "lastName": "maubila",
                      "email": "johndoe@example.com",
                      "address": "sikumana"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get":{
        "description": "mendapatkan 1 data contact berdasarkan id yang dipilih",
        "parameters": [
          {
            "$ref": "#/components/parameters/authorization"
          },
          {
            "$ref": "#/components/parameters/getWhereId"
          },
          {
            "name": "name",
            "in": "query",
            "description": "mendapatkan data berdasarkan firstname atau lastname",
            "required": false,
            "schema":{
              "type": "string"
            }
          },
          {
            "name": "phone",
            "in": "query",
            "description": "mendapatkan data berdasarkan nomor ponsel",
            "required": false,
            "schema":{
              "type": "number"
            }
          },
          {
            "name": "email",
            "in": "query",
            "description": "mendapatkan data berdasarkan email",
            "required": false,
            "schema":{
              "type": "string"
            }
          },
          {
            "name": "address",
            "in": "query",
            "description": "mendapatkan data berdasarkan address",
            "required": false,
            "schema":{
              "type": "string"
            }
          },
          {
            "name": "size",
            "in": "query",
            "description": "mendapatkan data berdasarkan size paging",
            "required": false,
            "schema":{
              "type": "string"
            }
          },
          {
            "name": "paging",
            "in": "query",
            "description": "mendapatkan data berdasarkan paging",
            "required": false,
            "schema":{
              "type": "string"
            }
          }
        ],
        "responses": {
          "200":{
            "description": "",
            "content": {
              "application/json":{
                "schema":{
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items":{
                        "type": "object",
                        "properties": {
                          "id":{
                            "type": "number"
                          },
                          "firstName":{
                            "type": "string"
                          },
                          "lastname":{
                            "type": "string"
                          },
                          "phone":{
                            "type": "string"
                          },
                          "email":{
                            "type": "string"
                          },
                          "address":{
                            "type": "string"
                          }
                        }
                      }
                    },
                    "meta":{
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete":{
        "description": "menghapus 1 data contact berdasarkan id yang dipilih",
        "parameters": [
          {
            "$ref": "#/components/parameters/authorization"
          },
          {
            "$ref": "#/components/parameters/getWhereId"
          }
        ],
        "responses": {
          "200": {
            "description": "berhasil menyimpan data ke sistem",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "boolean"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "authorization":{
        "name": "authorization",
        "in": "header",
        "description": "authentication checking",
        "required": true,
        "schema":{
          "type": "string"
        }
      },
      "getWhereId":{
        "name": "id",
        "in": "path",
        "description": "get data where id",
        "required": true,
        "schema":{
          "type": "number"
        }
      }
    },
    "responses": {

    }
  }
}

